services:
  sample_metadata_input_app:
    image: ghcr.io/als-computing/sample_metadata_input_app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80