services:
  sample_metadata_app-frontend:
    image: ghcr.io/als-computing/sample_metadata_app-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80